# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Akubi05's Blog
subtitle: Akubi05的博客
description: 一个记录生活点滴的地方
keywords: Akubi05, 博客, Hexo, 个人博客
author: Akubi05
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://Akubi05.github.io  # 你的网站地址，如果是 GitHub Pages，建议改为：https://Akubi05.github.io

permalink: :year/:month/:day/:title/  # 博文的永久链接格式
permalink_defaults:                  # 用于设置默认值（一般不需要）
pretty_urls:
  trailing_index: true               # 是否保留 index.html 后缀
  trailing_html: true                # 是否保留 .html 后缀

# Directory
source_dir: source       # 原始文件目录
public_dir: public       # 生成的静态网站目录
tag_dir: tags            # 标签页面目录
archive_dir: archives    # 归档页面目录
category_dir: categories # 分类页面目录
code_dir: downloads/code # 下载代码目录
i18n_dir: :lang          # 多语言目录
skip_render:             # 不渲染的文件（可写路径或通配符）

# Writing
new_post_name: :title.md   # 新文章的文件名
default_layout: post       # 默认布局（可选 page/post）
titlecase: false           # 是否标题首字母大写
external_link:             # 外链设置
  enable: true
  field: site              # 只对整个站点生效
  exclude: ''
filename_case: 0           # 文件名是否强制大小写（0=不处理，1=小写，2=大写）
render_drafts: false       # 是否渲染草稿
post_asset_folder: false   # 是否启用文章资源文件夹
relative_link: false       # 是否使用相对路径
future: true               # 是否显示未来的文章
syntax_highlighter: highlight.js  # 语法高亮工具，可选 highlight.js / prismjs / false
highlight:
  line_number: true
  auto_detect: true
  enable: false
  tab_replace: ''
  wrap: true
  # hljs: false
  hljs: true
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''               # 首页路径，默认是根目录
  per_page: 10           # 每页显示文章数
  order_by: -date        # 排序方式，-date 表示倒序（最新文章在前）


# Category & Tag
default_category: uncategorized
category_map:            # 分类别名映射
tag_map:                 # 标签别名映射
  # example:
  #   JavaScript: js
  #   Python: py

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD     # 日期显示格式
time_format: HH:mm:ss       # 时间显示格式
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'     # 文章更新时间来源（mtime=文件修改时间）


# Pagination
## Set per_page to 0 to disable pagination
per_page: 10                # 每页文章数量（0表示不分页）
pagination_dir: page        # 分页目录名（默认 page/2, page/3 ...）

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:                    # 指定 source 中的文件强制包含（可用通配符）
exclude:                    # 指定 source 中的文件不生成
ignore:                     # 忽略的文件（更高优先级）

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
# theme: tangyuxian           # 当前使用的主题名，对应 themes/tangyuxian
theme: hexo-theme-butterfly-dev

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:Akubi05/Akubi05.github.io.git
  # repo: https://github.com/Akubi05/Akubi05.github.io.git
  branch: main